### ISSUE TITLE
Same code, error in 1st VPS but fine in 2nd

### ISSUE THREAD

**Issue by neochine** [cohere-ai/cohere-python#573]
```
root@x1:~# cat website.py
import os
import cohere

cohere_api_key = os.getenv('COHERE_API_KEY')
co = cohere.Client(cohere_api_key)

response = co.chat(
    model="command-r-plus",
    message="Hey I want to create !"
)

print(response)


root@x1:~# python3.11 website.py
/usr/lib/python3/dist-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (5.1.0)/charset_normalizer (3.0.1) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/cohere/base_client.py", line 1071, in chat
    object_=_response.json(),
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/website.py", line 7, in <module>
    response = co.chat(
               ^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/cohere/client.py", line 103, in _wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/cohere/client.py", line 35, in _wrapped
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/cohere/base_client.py", line 1157, in chat
    raise ApiError(status_code=_response.status_code, body=_response.text)
cohere.core.api_error.ApiError: status_code: 403, body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
```
```
root@x2:~# cat website.py

import os
import cohere

cohere_api_key = os.getenv('COHERE_API_KEY')
co = cohere.Client(cohere_api_key)

response = co.chat(
        message="hello world!"
)

print(response)
root@x2:~# python3.11 website.py
/usr/lib/python3/dist-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (5.1.0)/charset_normalizer (3.0.1) doesn't match a supported version!
  warnings.warn(
text='Hello! How can I help you today?' generation_id='9ab327d6-.....-b9cfbb5fa5c3' citations=None documents=None is_search_required=None search_queries=None search_results=None finish_reason='COMPLETE' tool_calls=None chat_history=[Message_User(role='USER', message='hello world!', tool_calls=None), Message_Chatbot(role='CHATBOT', message='Hello! How can I help you today?', tool_calls=None)] prompt=None meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(input_tokens=3.0, output_tokens=9.0, search_units=None, classifications=None), tokens=ApiMetaTokens(input_tokens=209.0, output_tokens=9.0), warnings=None) response_id='c45db2c7-.....4af242d965fd'
```

**Comment by neochine** [comment]
Changing 1st vps code by removing model="command-r-plus" still gives same `cohere.core.api_error.ApiError: status_code: 403, body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden`

**Comment by manuel-cohere** [comment]
Hello @neochine ,

Can you please share IP details via email to security@cohere.com ?

Thank you!

**Comment by neochine** [comment]
Sent @manuel-cohere

**Comment by manuel-cohere** [comment]
I don't see any more traffic being blocked from the IPs you shared. I'll close the ticket :)
