### ISSUE TITLE
Error in embedding model id

### ISSUE THREAD

**Issue by khalid4294** [cohere-ai/cohere-python#590]
cohere==5.1.2

We're trying to run an embed job through the python client, and we're getting this error:

`{'message': "model 'packed-embed-multilingual-light-v3.0-bulkjob' not found, make sure the correct model ID was used and that you have access to the model."}
`
although we're using the correct model name: **"embed-multilingual-light-v3.0"**

Traceback: 

```
[09:00:41] [INFO] [dku.utils]  - Traceback (most recent call last):
[09:00:41] [INFO] [dku.utils]  -   File "/opt/dataiku/python/dataiku/container/exec_py_recipe.py", line 15, in <module>
[09:00:41] [INFO] [dku.utils]  -     exec(fd.read())
[09:00:41] [INFO] [dku.utils]  -   File "<string>", line 34, in <module>
[09:00:41] [INFO] [dku.utils]  -   File "/home/dataiku/lib/project/project-python-libs/SMART_SEARCH/python/text_processing/embedding.py", line 122, in create_embed_job
[09:00:41] [INFO] [dku.utils]  -     embed_job = self.co.embed_jobs.create(
[09:00:41] [INFO] [dku.utils]  -   File "/opt/dataiku/code-env/lib/python3.9/site-packages/cohere/embed_jobs/client.py", line 174, in create
[09:00:41] [INFO] [dku.utils]  -     raise ApiError(status_code=_response.status_code, body=_response_json)
[09:00:41] [INFO] [dku.utils]  - cohere.core.api_error.ApiError: status_code: 404, body: {'message': "model 'packed-embed-multilingual-light-v3.0-bulkjob' not found, make sure the correct model ID was used and that you have access to the model."}
```

**Comment by mkozakov** [comment]
This should have been addressed. @khalid4294 can you please confirm?

**Comment by khalid4294** [comment]
yes, it's fixed, thanks!
